version: '3'
services:
  serverless:
    image: serverless
    entrypoint: serverless
    working_dir: /var/app
    ports:
    - "3000:3000"
    volumes:
    - .:/var/app 
    environment:
    - AWS_ACCESS_KEY_ID=
    - AWS_SECRET_ACCESS_KEY=